# Generated by Django 5.2.5 on 2025-08-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
