# Generated by Django 5.2.5 on 2025-08-14 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=1)),
                ('item_id', models.BigIntegerField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=1)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
