# Generated by Django 5.2.5 on 2025-08-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item_title',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='item_type',
            field=models.CharField(choices=[('T', '시험'), ('C', '수업')], max_length=1),
        ),
    ]
