# Generated by Django 5.2.5 on 2025-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_item_title_alter_payment_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
    ]
