# Generated by Django 5.2.5 on 2025-08-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_discounted_price_payment_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='original_price',
            field=models.IntegerField(),
        ),
    ]
