# Generated by Django 5.2.5 on 2025-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='original_price',
        ),
        migrations.AlterField(
            model_name='payment',
            name='item_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
