# Generated by Django 5.2.5 on 2025-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discounted_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
