# Generated by Django 5.2.5 on 2025-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ended_at',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='started_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='test',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
