# Generated by Django 5.2.5 on 2025-08-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_rename_ended_at_test_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='completed',
        ),
    ]
