# Generated by Django 5.2.5 on 2025-08-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
