# Generated by Django 5.2.5 on 2025-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_registrations', '0002_courseregistration_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
